finchcollector/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls'))
]

main_app/urls.py
from django.urls import path
from . import views

# how we map our urls to views
# views are the 'controllers', they map http request to code. This file is how we match those requests to specific urls.
# `name = 'home'` is a kwarg, which gives the route a name. 
urlpatterns = [
  path('', views.home, name='home'),
  path('about/', views.about, name='about'),
  # index route
  path('finches/', views.finches_index, name='index'),
  # DON'T FUCK THIS UP YOU'LL NEED IT FOR THE PROJECT
  # detail route
  # need an id + the ability to refer to the id
  path('finches/<int:finch_id>', views.finches_detail, name='detail'),
  path('finches/create', views.FinchCreate.as_view(), name='finches_create'),
  path('finches/<int:pk>/update', views.FinchUpdate.as_view(), name='finches_update'),
  path('finches/<int:pk>/delete', views.FinchDelete.as_view(), name='finches_delete')

]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date

# Create your models here.
MEALS = (
  ('B', 'Breakfast'),
  ('L', 'Lunch'),
  ('D', 'Dinner'),
) 

# finch model
class Finch(models.Model):
  species = models.CharField(max_length=100)
  population = models.CharField(max_length=50)
  habitat = models.CharField(max_length=100)
  about = models.TextField(max_length=250)
  def __str__(self):
    return self.species
  def get_absolute_url(self):
    return reverse('detail', kwargs={'finch_id': self.id})
#
  
class Feeding(models.Model):
  date = models.DateField('feeding date')
  meal = models.CharField(
    max_length=1,
    choices=MEALS,
    default=MEALS[0][0]
  )
  finch = models.ForeignKey(Finch, on_delete=models.CASCADE)
  def __str__(self):
    return f"{self.get_meal_display()} on {self.date} for {self.finch}"
  class Meta:
    ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Feeding

class FeedingForm(ModelForm):
  class Meta:
    model = Feeding
    fields = ['date', 'meal']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from .models import Finch
from .forms import FeedingForm


# finches = [
#   {'species': 'Lolo', 'population': 'tabby', 'habitat': 'furry little demon', 'note': 3},
#   {'species': 'Sachi', 'breed': 'calico', 'description': 'gentle and loving', 'age': 2},
# ]

# Create your views here.

# define home view here - '/'
# GET - Home
def home(request):
  #remember to include the .html file extension
  return render(request, 'home.html')

def about(request):
  return render(request, 'about.html')

# index view
def finches_index(request):
  finches = Finch.objects.all()
  for finch in finches:
    print(finch)
  return render(request, 'finches/index.html', { 'finches': finches })

# detail view
def finches_detail(request, finch_id):
  # YOU'RE GONNA NEED THIS ISH FOR THE PROJECT
  # THE ID COMES FROM THE URL. PAY ATTENTION DUDE
  finch = Finch.objects.get(id=finch_id)

  return render(request, 'finches/detail.html', { 'finch': finch})

class FinchCreate(CreateView):
  model = Finch
  fields = '__all__'
  success_url = 'finches/{finch_id}'
  
class FinchUpdate(UpdateView):
  model = Finch
  fields = ['population', 'habitat', 'about']

class FinchDelete(DeleteView):
  model = Finch
  success_url = '/finches'

def add_feeding(request, finch_id):
  form = FeedingForm
  if form.is_valid():
    new_feeding = form.save(commit=False)
    new_feeding.cat_id = finch_id
    new_feeding.save()
  return redirect('detail', finch_id=finch_id)

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

  <h1>About the Finch Collector</h1>
  <hr>
  <p>It's a Finch Collector. Finches are birds of sorts</p>

{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Finch Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li>
            <a href="/" class="left brand-logo">
              &nbsp;&nbsp;Finch Collector
            </a>
          </li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'index' %}">Finches</a></li>
          <li><a href="{% url 'finches_create' %}">Add a Finch</a></li>
          <li><a href="{% url 'about' %}">About</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    
    
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">
      All Rights Reserved, &copy; 2024 Finch Collector &nbsp;
    </div>
  </footer>
</body>

</html>

main_app/templates/finches/detail.html
{% extends 'base.html' %}
{% block content %}

  <h1>Details about {{finch.species}}</h1>
  <div class="card">
    <div class="card-content">
      <span class="card-title">{{finch.species}}</span>
      <p>Population: {{finch.population}}</p>
      <p>Habitat: {{finch.habitat}}</p>
      <p>About: {{finch.note}}</p>
    </div>
    <div class="class-action">
      <a href="{% url 'finches_update' finch.id %}">Update</a>
      <a href="{% url 'finches_delete' finch.id %}">Delete</a>
    </div>
  </div>
  <div>
    <table class="striped">
      <thead>
        <tr><th>Date</th><th>Meal</th></tr>
      </thead>
      <tbody>
        {% for feeding in finch.feeding_set.all %}
          <tr>
            <td>{{feeding.date}}</td>
            <td>{{feeding.get_meal_display}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

main_app/templates/finches/index.html
{% extends 'base.html' %}
{% block content %}

  <h1>Finch List</h1>

  {% for finch in finches %}
    <div class="card">
      <a href="{% url 'detail' finch.id %}">
        <div class="card-content">
          <span class="card-title">{{finch.species}}</span>
          <p>Population: {{finch.population}}</p>
          <p>Habitat: {{finch.habitat}}</p>
          <p>About: {{finch.note}}</p>
        </div>
      </a>
    </div>
  {% endfor %}

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

  <h1>Home</h1>

{% endblock %}

main_app/templates/main_app/finch_confirm_delete.html
{% extends 'base.html' %}
{% block content%}

  <h3>Delete Finch</h3>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.species }}</span>?</h4>
  
  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes! - Delete" class="btn">
    <a href="{% url 'detail' finch.id %}" class="btn red">Cancel</a>
  </form>

{% endblock %}

main_app/templates/main_app/finch_form.html
{% extends 'base.html' %}
{% block content %}

  {% if object %}
    <h3>Edit {{ object.species }}</h3>
  {% else %}
    <h3>Add a Finch</h3>
  {% endif %}
  
  <form action="" method="POST">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>

{% endblock %}